version: '3.7'

services:
  notifications-postgres:
    image: postgres
    container_name: database_notifications-service_messager
    ports:
      - 5454:5454
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=notifications
    volumes:
      - pgdata:/data/postgres
    command: -p 5454

volumes:
  pgdata:
    driver: local